apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fanworkersink

resources:
  - namespace.yaml
  - localstack-deployment.yaml
  - localstack-service.yaml
  - localstack-init-cm.yaml

secretGenerator:
  - name: aws-credentials
    type: Opaque
    literals:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
